packages:
  - apps/*
  - packages/core
  - packages/react
  - packages/vue
  - packages/vanilla
  - packages/next
  - packages/preact
  - packages/solid
  - packages/svelte
  - packages/qwik
  - packages/angular
  - packages/server
