packages:
  - apps/*
  - packages/core
  - packages/react
  - packages/vue
  - packages/svelte
  - packages/vanilla
  - packages/angular
  - packages/server
  - packages/interactive-example
  - packages/storybook-config
  - packages/tailwind-config
  - packages/preact
  - packages/next
