import type { CategoryDefinition } from '../types'

export const appearanceCategory: CategoryDefinition = {
    id: 'appearance',
    label: 'Appearance',
    description: 'Theme mode, tokens, and per-slot overrides',
    entries: [
        {
            id: 'theme.mode',
            label: 'Theme mode',
            primitive: 'enum',
            defaultValue: 'system',
            options: { options: ['light', 'dark', 'system'], layout: 'segmented' },
        },
        {
            id: 'theme.tokens.color.primary',
            label: 'Primary color',
            primitive: 'color',
            defaultValue: '',
            options: { placeholder: '#30C5F7' },
        },
        {
            id: 'theme.slots',
            label: 'Slot overrides (className strings)',
            description: 'Target any internal element with custom classes — Tailwind utilities or plain CSS names. Empty slots keep the built-in styling. See the Theming guide for the full slot map.',
            primitive: 'nested',
            defaultValue: undefined,
            options: {
                fields: [
                    {
                        id: 'uploader.container',
                        label: 'uploader.container',
                        description: 'Outermost wrapper around the entire uploader tree.',
                        primitive: 'string',
                        defaultValue: '',
                        options: { placeholder: 'rounded-2xl border shadow-lg' },
                    },
                    {
                        id: 'fileList.root',
                        label: 'fileList.root',
                        description: 'The scrollable list shown after files are added.',
                        primitive: 'string',
                        defaultValue: '',
                        options: { placeholder: 'bg-slate-50 dark:bg-slate-900' },
                    },
                    {
                        id: 'fileList.uploadButton',
                        label: 'fileList.uploadButton',
                        description: 'Primary "Upload N files" button at the bottom of the list.',
                        primitive: 'string',
                        defaultValue: '',
                        options: { placeholder: 'bg-indigo-600 hover:bg-indigo-700 text-white' },
                    },
                    {
                        id: 'filePreview.deleteButton',
                        label: 'filePreview.deleteButton',
                        description: 'Per-file remove (X) button on the preview tile.',
                        primitive: 'string',
                        defaultValue: '',
                        options: { placeholder: 'opacity-60 hover:opacity-100' },
                    },
                    {
                        id: 'progressBar.fill',
                        label: 'progressBar.fill',
                        description: 'The filled part of the per-file progress bar.',
                        primitive: 'string',
                        defaultValue: '',
                        options: { placeholder: 'bg-gradient-to-r from-cyan-400 to-blue-500' },
                    },
                    {
                        id: 'sourceSelector.adapterButton',
                        label: 'sourceSelector.adapterButton',
                        description: 'The row of source tiles (Device, Google Drive, Camera, …).',
                        primitive: 'string',
                        defaultValue: '',
                        options: { placeholder: 'rounded-lg ring-1 ring-slate-200' },
                    },
                    {
                        id: 'sourceView.header',
                        label: 'sourceView.header',
                        description: 'Header strip shown while a drive/camera picker is open.',
                        primitive: 'string',
                        defaultValue: '',
                        options: { placeholder: 'border-b border-slate-200 px-4' },
                    },
                    {
                        id: 'urlUploader.fetchButton',
                        label: 'urlUploader.fetchButton',
                        description: 'The fetch-URL action button inside the Link source.',
                        primitive: 'string',
                        defaultValue: '',
                        options: { placeholder: 'bg-slate-900 text-white' },
                    },
                ],
            },
        },
        {
            id: 'className',
            label: 'Root className',
            description: 'Applied to the uploader\'s top-level container. Quick way to size / position the whole component without touching slots.',
            primitive: 'string',
            defaultValue: '',
            options: { placeholder: 'max-w-2xl mx-auto' },
        },
    ],
}
