// Bundles src/worker/pipeline-worker.ts (+ heic2any + image-utils) into a
// self-contained IIFE string and writes it to src/worker/pipeline-worker.code.ts.
// Runs as a `build` prebuild step before tsup, so the generated module exists
// when tsup follows core.ts's `import('./worker/pipeline-worker.code')`.
import { build } from 'esbuild'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const entry = resolve(here, '../src/worker/pipeline-worker.ts')
const outFile = resolve(here, '../src/worker/pipeline-worker.code.ts')

const result = await build({
  entryPoints: [entry],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2019',
  minify: true,
  write: false,
})

const code = result.outputFiles[0].text
mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(
  outFile,
  `// AUTO-GENERATED by scripts/build-worker.mjs — do not edit, do not commit.\n` +
    `export const PIPELINE_WORKER_CODE = ${JSON.stringify(code)}\n`,
)
console.log(`[build-worker] wrote ${outFile} (${code.length} bytes)`)
