export type UploaderClassNames = {
  fileIcon?: string
  containerMini?: string
  containerFull?: string
  containerHeader?: string
  containerCancelButton?: string
  containerAddMoreButton?: string
  adapterButtonList?: string
  adapterButton?: string
  adapterButtonIcon?: string
  adapterButtonText?: string
  adapterViewHeader?: string
  adapterViewCancelButton?: string
  adapterView?: string
  driveLoading?: string
  driveHeader?: string
  driveLogoutButton?: string
  driveSearchContainer?: string
  driveSearchInput?: string
  driveBody?: string
  driveItemContainerDefault?: string
  driveItemContainerSelected?: string
  driveItemContainerInner?: string
  driveItemInnerText?: string
  driveFooter?: string
  driveAddFilesButton?: string
  driveCancelFilesButton?: string
  urlInput?: string
  urlFetchButton?: string
  cameraPreviewContainer?: string
  cameraDeleteButton?: string
  cameraCaptureButton?: string
  cameraRotateButton?: string
  cameraMirrorButton?: string
  cameraAddButton?: string
  cameraModeToggle?: string
  cameraVideoRecordButton?: string
  cameraVideoStopButton?: string
  cameraVideoPreview?: string
  cameraVideoAddButton?: string
  cameraVideoDeleteButton?: string
  audioRecordButton?: string
  audioStopButton?: string
  audioPlaybackContainer?: string
  audioWaveform?: string
  audioAddButton?: string
  audioDeleteButton?: string
  screenCaptureContainer?: string
  screenCaptureStartButton?: string
  screenCaptureStopButton?: string
  screenCapturePreview?: string
  screenCaptureAddButton?: string
  screenCaptureDeleteButton?: string
  fileListContainer?: string
  fileListContainerInnerSingle?: string
  fileListContainerInnerMultiple?: string
  fileListFooter?: string
  filePreviewPortal?: string
  fileItemSingle?: string
  fileItemMultiple?: string
  fileThumbnailSingle?: string
  fileThumbnailMultiple?: string
  fileInfo?: string
  fileName?: string
  fileSize?: string
  filePreviewButton?: string
  fileDeleteButton?: string
  uploadButton?: string
  uploadDoneButton?: string
  progressBarContainer?: string
  progressBar?: string
  progressBarInner?: string
  progressBarText?: string
}
